"""وارد کردن دسته‌جمعیِ لیست کانال‌ها به دیتابیس سرور — این‌ها فوراً join
نمی‌شن؛ چرخه‌ی sync_channels (که از قبل تو collector.py در حال اجراست)
خودش به‌ترتیب و با فاصله‌ی زمانی مناسب (برای جلوگیری از FloodWait) بهشون
می‌پیونده.

اجرا:
    $env:PYTHONPATH="src"
    py import_channels.py
"""

import sys

sys.path.insert(0, "src")

from telegramonline.config import Settings
from telegramonline.storage import add_channel, connect

USERNAMES = """
AMIRKALHOR1357
ARADKHODRO96
AUTONIKRANTAHAMTAN
AUTOSAJADQOM
AUTO_TEYMOURI
AUTO_YOUSEFI
AUTO_pashabadi1126
AUTOvahidkohzadi7002
Agent_saipa_dayyani
AlborzCar_68
Alidavarancar
AmirHossein_soroush
Amiresmaielihamedan
Ardeshir94babaei
ArmanKhdro
Artashkhodroqom
Askari_havale_sefr
Ati_Khodro1
AutoAlikarimi
AutoAlmasi
AutoArakQomTehran
AutoBERLIN1
AutoEightAsgarinia
AutoKomiL
AutoPiran
AutoRA_sbz
AutoYousefii401
Auto_Delsi
Auto_Gallery_Azadi
Auto_Nazari0152
Auto_Roysa_16
Auto_Tehrann
Auto_alizad
Auto_galery_danesh
Auto_jahangiry_qom
Auto_khodroplus
Auto_lotus_bargrizan
Auto_tashrifat_eslami
Autoalmas3
Autoarad2
Autocarbaleghi
Autokarimi_salmani
AutomobilKakaei
Autorezae
Autosherkat
Autosoltaniii
Car_center_Caren
Cars_Qom
Faraaz_khodro
Farhadrezaei741khodrosefr
Fazeli_carsale
Gallerykhodro_HaBiBi
HAMEGANICARSHAMEDAN18
HazratiCarCenter
IJADKHODRO
IRANKHODROMONIRIKASHAN
JavanrudCars
Khodrohajiloo
Khodrosefr_khani_karaj8
Kourosh_Gallry
Machingram
Mahan_Cars
Marcazi
Masoud_elyasian69
Mehranshahabicar
Meysammoqise
Miniuta_khodro
Moorselimohamad
New_khodro_qom
OTOLANDGALLERY
Otomobilgafari
Outosalehkarahrodi
Parastesh_mosavi
Payamrahnama
Radkhudro
Radwin_Khodro
Razhis_khodro
Reza_arefzade
RezadavaranCAR
RezaeiAutoGallery
Sadegh_khodro
Samikhodrohajialyani
Sefaresh_Modiran
ShahryarCars98
Teslatalei
abharkhodroo
alavicarexhibition
ali_neisi74
alifallla
aligharebagi
amirhoseinghodratigallery
amirhoseinlasheycarsell
amirshakibacar
arakolampic
aranmeshkin
arasmehri
argirankhodrosharify
ariangoomar
armancars
arsamkhodroav
aryancar0900
asghari_khodro
atilakhodro
atraskhodro
atuopayman
aturamezaniiabedini3456
auto7seven
autoMohajerani
autoMohammadNabati
autoSaeed1405724
autoZeraieQom
auto_Kaviyanii77
auto_ahmadvand
auto_amatiss
auto_aseman_sarab58
auto_azad_karaj
auto_darab
auto_dayy
auto_galeri_pershian
auto_gallery_asgharrashidi
auto_gallery_shahan1
auto_gallerymahdi
auto_gallry_pedram
auto_hajiesmaili
auto_kouhnvrd
auto_mahdavii
auto_manof
auto_melk_plusqom
auto_nazari
auto_paytakhtt
auto_rostamlou
auto_saran
auto_sefr_derakhshan
auto_sefr_mehran_noorzade
auto_sohrabi1
auto_yektaa
auto_zhiyan24
autoa_m
autoalirezasalamat
autoaminalinia
autoamirhossein_mehrjo
autoaslani
autofezolahi
autogalerimehrab
autogalery_makan
autogalerymhmood
autogalerymorteza
autogallery_mehdighasemi
autogallery_najafi
autogallerynesari
autogallerypouramini
autogalleryseyyd
autogallerysorani
autogandomi
autoghasemi14
autogm
autohamed70
autohamidgh
autohiradd
autohoseinoghli
autojabari1
autojalolipaytakht
autokarenahmadi
autokhademi2590
autokhosravii2009
autoland41
autoland_bayat
autolandkhoramabad
autoluxkhodaei
autoluxy
automakan_47
automehrabi
automeysamsaghi
automingallery
automirzai
autonajafi_qom
autoo_park
autoogold_turkeman
autopalasco
autoparham
autopark_bonab
autoprestigee
autorahmanpour
autosaba1446
autosalman09132603432
autosarafrazi
autosardarr
autosefr_mehrabani
autosefr_mohamadhajizade
autoshahreman
autotavako
autovalayati
autozabihi
autozarrin219
autux11
az09128542464
bakhtiyaricharcharkh
bazarkhodro3
behzad_fathiii
car_Hosseini
car_baba
car_hezha
car_molavi1
carabolfathi
carahmadi
carikco
carkhodrocar1
carnakhodrooo
carsangallery
carsell2022
damanicar
danialabbasiiii
davoodkelasii
deygallerry
dollar_tehran3bze
doosticar
ehsaaant
ehteshamn
eshraghicar
farhadiran18
farhankhodro
faribamokhtarycar
farsamkhodro
farzancar1
foroshaghsatykhodro
galeryarmani
gallery20moradi
gallery_ataie
gallery_farzadmoradi
gghfjftd824vtdjdf
habashikhodro
hajhosseinbagheri3312
hamedkohkanava
hamidvalizade11
hashemkaka
havale_aras_0077
havale_khodroo_qom
havale_nikdel_21
havalehcarpaytakht
havalehkhodroo2026
hirakhodroo
hoseinkhani17399
hoseinmahakii
htSanicar
httpstmejoinchatAAAAAEQmKF
ilam98khodro
imprial0
irankhodro14
irankodroohadiali
k1khodro
kabood_sefrkhodro
kashankhodrorahimi
keyvan_azari
keyvancar
khanifer_car_sales
kharakhodro
kharidforoshhkhodro
khazarrkhodro
khodro1030real
khodroRostami1
khodro_gerami
khodro_gharb
khodro_sefrr
khodro_tirgham
khodroebadi
khodrohasanpour
khodromomeni
khodronajafi
khodrosafarhasansori
khodrosarasadeghi
khodrosefr02
khodrosefrfathi
khoodroyabi
kiu2016
kurdestankhodro
luxurycar2
mamademami
mamatir_khodro_hosseini
marandi_car
maseodkodrelrstan
masoudAutoTehran
mehdinademi
mehdirahmatisefr
mehrdad_khodro777
miladautogallery1
mirzaii58
mobinkhodrooo
mohicars
mostafabeigicar
mousaviAutoKhan
najikhodro_malekpour_amiri
nezami_hamsafar
niikankhodro
nikanmorsalisoleymani
nikkhodropaytakht
nomonehtabriz
nyazi136262
omid_biyabani
online_auto_shop
optionalkhodro
oto_azarakhsh
otoadelkhani
otocarahmadi
otogallarymobin
otogalleriamraei
otogalrei_ideal
otohossini
otoldeal
otomellal
otomobileparsian
outo_kimia_qom
outo_land_2
outomotivegalery
pahlevanikhodroo
parsa_afshar_car
payaacar
pedalkhodroo
pedramkafaei
pejman2616
persiankhoodromostafaabyar
piryyyyy
pishro_car2022
radicalseaa
radvinkhodro_hossinkeahvarz
raeeszadeh1
rahimiauto
rahmaticar
rasouli09124493822
rezadavary_salecar
rezaee_khodro
saadaticar
sabakhodro2
saeid1582
saeid_najafi1
safaeimehr
safirkhodrou
sahand_mohammad_ali
sahracar
saipaIrankhodro
saipavairankhodro
samantahericarat
samen8575
sanatkhodro2
sarankhodro
sefrkhodro_miyaneh
sefrkhodrodarvishi
sepahradkhodroo
sh3070
shahabbesharaty
shahabmoghadam1
shahrokh_khodro_iranian
shakiba_iran_16
sharifkhodro
siamakricmanchiafshar
siyaacar
soheib_khodro
sourenacars
sourtmeh_car
tejarat_khodro_semnan
testikeyvan
tilestanikhodro
titan_khodro
vaazimikhodro
vahidasadiqom
vahidmolaei6884
wolfkhodro2
yarjanlicar
""".split()


def main() -> None:
    settings = Settings.from_env()
    conn = connect(settings.database_path)

    added = 0
    skipped = 0
    for username in USERNAMES:
        result = add_channel(conn, username)
        if result is not None:
            added += 1
        else:
            skipped += 1

    print(f"✅ تمام شد. {added} کانال اضافه شد، {skipped} رد شد (نامعتبر/تکراری).")
    print("چرخه‌ی sync_channels (تو ترمینال Collector) به‌مرور بهشون می‌پیونده.")


if __name__ == "__main__":
    main()
